### ISSUE TITLE
图片获取一直失败

### ISSUE THREAD

**Issue by monokuma233** [ssttkkl/PixivBot#13]
2020-11-27 01:22:29.733 | INFO     | handler.pixiv_illust_query_handler:generate_reply:42 - illust query: [85869703]
2020-11-27 01:22:30.541 | INFO     | handler.pixiv_illust_query_handler:make_msg:32 - illust query: [85869703] ok

<class 'pixivpy3.utils.PixivError'> requests GET https://i.pximg.net/img-original/img/2020/11/24/01/06/14/85869703_p0.jpg error: HTTPSConnectionPool(host='i.pximg.net', port=443): Max retries exceeded with url: /img-original/img/2020/11/24/01/06/14/85869703_p0.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)'

**Comment by monokuma233** [comment]
DNS配置的问题，SSL问题已解决。目前往调用mirai-api-http发送好友消息接口报错：
[{'type': 'Plain', 'text': '「'}, {'type': 'Plain', 'text': '花嫁鹿島'}, {'type': 'Plain', 'text': '」\ntags: '}, {'type': 'Plain', 'text': '鹿島(艦隊これくし ょん) ウェディングドレス ケッコンカッコカリ 艦これ 手袋 鹿島 艦これ5000users入り'}, {'type': 'Plain', 'text': '\nhttps://www.pixiv.net/artworks/'}, {'type': 'Plain', 'text': '85869703'}, {'type': 'Plain', 'text': '\n'}, {'type': 'Image', 'imageId': '/18446744071565475902-1028862697-4FFD2AD0090B4B29ED2D06636A43D242', 'url': 'http://c2cpicdw.qpic.cn/offpic_new/2150891582//18446744071565475902-1028862697-4FFD2AD0090B4B29ED2D06636A43D242/0?term=2', 'path': '/home/mirai/mcl-1.0.2/./data/MiraiApiHttp/images/img'}]
Traceback (most recent call last):
  File "/home/pixivbot/PixivBot-0.2.0/handler/abstract_message_handler.py", line 84, in on_receive
  ait reply(app, subject, msg, src)
  File "/home/pixivbot/PixivBot-0.2.0/utils/reply_queue.py", line 39, in reply
    await __reply_queue.do(partial(app.sendFriendMessage, target=subject, messag  message, quote=quote))
  File "/home/pixivbot/PixivBot-0.2.0/utils/wait_queue.py", line 16, in do
    return await fut
  File "/home/pixivbot/PixivBot-0.2.0/utils/wait_queue.py", line 22, in __worker
   res = await asyncio.wait_for(func(), timeout=self.timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 476, in wait_for
    return fut.result()
  File "/home/pixivbot/.local/lib/python3.9/site-packages/graia/application/util  Fipy", line 15, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/pixivbot/.local/lib/python3.9/site-packages/graia/application/__in  Fi.py", line 407, in sendFriendMessage
    response.raise_for_status()
  File "/home/pixivbot/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.  Fi line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://localhost:8000/sendFriendMessage')

**Comment by monokuma233** [comment]
网络问题，已解决。

**Comment by ssttkkl** [comment]
> DNS配置的问题，SSL问题已解决。目前往调用mirai-api-http发送好友消息接口报错：
> [{'type': 'Plain', 'text': '「'}, {'type': 'Plain', 'text': '花嫁鹿島'}, {'type': 'Plain', 'text': '」\ntags: '}, {'type': 'Plain', 'text': '鹿島(艦隊これくし ょん) ウェディングドレス ケッコンカッコカリ 艦これ 手袋 鹿島 艦これ5000users入り'}, {'type': 'Plain', 'text': '\nhttps://www.pixiv.net/artworks/'}, {'type': 'Plain', 'text': '85869703'}, {'type': 'Plain', 'text': '\n'}, {'type': 'Image', 'imageId': '/18446744071565475902-1028862697-4FFD2AD0090B4B29ED2D06636A43D242', 'url': 'http://c2cpicdw.qpic.cn/offpic_new/2150891582//18446744071565475902-1028862697-4FFD2AD0090B4B29ED2D06636A43D242/0?term=2', 'path': '/home/mirai/mcl-1.0.2/./data/MiraiApiHttp/images/img'}]
> Traceback (most recent call last):
> File "/home/pixivbot/PixivBot-0.2.0/handler/abstract_message_handler.py", line 84, in on_receive
> ait reply(app, subject, msg, src)
> File "/home/pixivbot/PixivBot-0.2.0/utils/reply_queue.py", line 39, in reply
> await __reply_queue.do(partial(app.sendFriendMessage, target=subject, messag message, quote=quote))
> File "/home/pixivbot/PixivBot-0.2.0/utils/wait_queue.py", line 16, in do
> return await fut
> File "/home/pixivbot/PixivBot-0.2.0/utils/wait_queue.py", line 22, in __worker
> res = await asyncio.wait_for(func(), timeout=self.timeout)
> File "/usr/local/lib/python3.9/asyncio/tasks.py", line 476, in wait_for
> return fut.result()
> File "/home/pixivbot/.local/lib/python3.9/site-packages/graia/application/util Fipy", line 15, in wrapper
> return await func(self, *args, **kwargs)
> File "/home/pixivbot/.local/lib/python3.9/site-packages/graia/application/__in Fi.py", line 407, in sendFriendMessage
> response.raise_for_status()
> File "/home/pixivbot/.local/lib/python3.9/site-packages/aiohttp/client_reqrep. Fi line 1000, in raise_for_status
> raise ClientResponseError(
> aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://localhost:8000/sendFriendMessage')

经过测试是消息长度过长导致的
