### ISSUE TITLE
配置mongo_helper时验证错误

### ISSUE THREAD

**Issue by as6296463** [ssttkkl/PixivBot#24]
因为没有接触过MongoDB，按网上的教程在腾讯云连接好和创建用户数据库后启动mongo_helper出现验证错误，但是去mongo查看用户和数据库都已创建好，请问是哪里出问题了。
![01](https://user-images.githubusercontent.com/37761817/140635433-1d0200b5-066c-43fc-895f-30971ea5610a.png)
![02](https://user-images.githubusercontent.com/37761817/140635440-594360d9-fcd6-415e-aa12-c86a0fe49c35.png)
![03](https://user-images.githubusercontent.com/37761817/140635445-60482caa-5e38-4df5-98ac-bf1633c97ef0.png)

**Comment by ssttkkl** [comment]
不懂捏
