### ISSUE TITLE
推荐插画系列报错，包括“来张图”和订阅

### ISSUE THREAD

**Issue by Putarku** [ssttkkl/PixivBot#31]
![image](https://user-images.githubusercontent.com/66679443/156914757-455b1e52-5583-41f0-9179-dda78f866112.png)
除此之外的其他功能是正常的

**Comment by ssttkkl** [comment]
已修复
问题出自CacheManager在某次从远程获取失败后没有在waiting中删除该请求，导致以后有相同请求时直接读取到获取失败的错误
