### ISSUE TITLE
不存在命令 'watch'

### ISSUE THREAD

**Issue by GHSSeBi** [ssttkkl/PixivBot#46]
不知道是不是我使用方法不对？
![1](https://user-images.githubusercontent.com/67882684/195630728-3de24871-4c3c-48bf-9a18-cfc1397ace9b.PNG)
![2](https://user-images.githubusercontent.com/67882684/195630758-5677b1ba-8dfa-46dc-839e-2eb7b9d1826f.PNG)

**Comment by ssttkkl** [comment]
拉最新版试试？反向驱动器之前镜像后缀写错了
