### ISSUE TITLE
拉取新版镜像后无法启动容器

### ISSUE THREAD

**Issue by SakuraQuck** [ssttkkl/PixivBot#48]
![1](https://user-images.githubusercontent.com/67882684/198072173-454e9250-7d90-465d-ba6c-e712b2eb8f29.png)
之前还可以用的，重新拉取镜像之后就无法启动容器了

**Comment by ssttkkl** [comment]
之前有个版本是忘记添加httpx依赖了，现在最新版已经修复了，你再重新pull试试

**Comment by SakuraQuck** [comment]
> 之前的版本是忘记添加httpx依赖了，现在最新版已经修复了，你再重新拉一下

重新拉取还是报一样的错

**Comment by SakuraQuck** [comment]
我拉的是re

**Comment by ssttkkl** [comment]
把httpx加上了

**Comment by SakuraQuck** [comment]
> 把httpx加上
可以了谢谢
